//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWAS2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWAS2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;multilang language=&quot;English(en-US)&quot;&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Desktop Wallpaper Auto Switch&lt;/key&gt;
        ///    &lt;value&gt;Desktop Wallpaper Auto Switch&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Desktop Orientation:&lt;/key&gt;
        ///    &lt;value&gt;Desktop Orientation:&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Landscape&lt;/key&gt;
        ///    &lt;value&gt;Landscape&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Portrait&lt;/key&gt;
        ///    &lt;value&gt;Portrait&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Fill&lt;/key&gt;
        ///    &lt;value&gt;Fill&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dwas2_en_US {
            get {
                return ResourceManager.GetString("dwas2_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;multilang language=&quot;中文(zh-CN)&quot;&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Desktop Wallpaper Auto Switch 2&lt;/key&gt;
        ///    &lt;value&gt;桌面背景自动切换2&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Current Orientation:&lt;/key&gt;
        ///    &lt;value&gt;当前屏幕方向：&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Landscape&lt;/key&gt;
        ///    &lt;value&gt;水平&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Portrait&lt;/key&gt;
        ///    &lt;value&gt;垂直&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Browse&lt;/key&gt;
        ///    &lt;value&gt;浏览&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;key&gt;Fill&lt;/key&gt;
        ///    &lt;value&gt;填充&lt;/value&gt;
        ///  &lt;/en [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dwas2_zh_CN {
            get {
                return ResourceManager.GetString("dwas2_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon landscape_icon {
            get {
                object obj = ResourceManager.GetObject("landscape_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon portrait_icon {
            get {
                object obj = ResourceManager.GetObject("portrait_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon span_48p {
            get {
                object obj = ResourceManager.GetObject("span_48p", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
